### ISSUE TITLE
Unable to play videos at speeds other than 1x on Firefox.

### ISSUE THREAD

**Issue by Sehzhar** [vatara/firefox-audio-compressor#1]
Basically as the title says, this addon disables other playback speeds on YouTube, don't know about other sites.

**Comment by vatara** [comment]
You are correct, unfortunately this is a Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1517199
Any AudioNode will block playbackRate from changing(in Firefox). It does seem to work correctly in Chrome. It's a two year old bug, but maybe it will get fixed soon. :(

**Comment by firagabird** [comment]
As of 2021-06-02/FF 91, the bug has apparently been fixed. After downloading the latest public version of FF 91 (on beta), the issue has indeed been resolved. Once it lands on stable, I'd consider it fixed on the end user side. Then again, since it's a Firefox bug, I'd close it if I were the dev.

**Comment by vatara** [comment]
Great, thanks for the update. I'll check it out when gets to stable.
