### ISSUE TITLE
Update broke the settings window on Chromium based browsers

### ISSUE THREAD

**Issue by 3941** [vatara/firefox-audio-compressor#12]
I feel bad for making another issue, especially after initiating the last update, but here I am 😅 

Tested in my default browser, Edge, and also in Brave, because I had it installed.
Looks exactly the same in both of them. And that's like this:
![image](https://github.com/vatara/firefox-audio-compressor/assets/8452538/70378ef0-4520-4f06-8fa2-fecece05adb0)

**Comment by 3941** [comment]
I assume it's that 0.1.23 update that hadn't been released on Chromium before.
The description definitely matches.
![image](https://github.com/vatara/firefox-audio-compressor/assets/8452538/31604703-1af6-4586-b1e8-9d29b7567a61)

**Comment by 3941** [comment]
Oh, and while we're at it... It seems it lost the settings I had made?
I first noticed the update because of a stark change in volume when I played a YT video.
From the little I can see of the interface, it looks like it was disabled, though it should be auto enabled for YT.
I'm pretty sure it also sounds different when I enable it.

Sorry for the spam 😓

**Comment by Popslip** [comment]
Same issue here, not isolated to this user.

**Comment by vatara** [comment]
Should have tested that 0.1.23 change on Chromium :(
At least it's easily reproducible...I just published the fix to the Chrome store, hopefully it gets approved soon.

**Comment by 3941** [comment]
Update already published and everything is fine now!
It did actually retain my settings.
New boost range is great!
Thanks again!
