### ISSUE TITLE
Longer release times

### ISSUE THREAD

**Issue by MMMXXXZZZ** [vatara/firefox-audio-compressor#15]
Is it possible to add a feature to set a longer Release value? With some content, 1 second going up and down everytime someone stops talking for a second can be nauseating (metaphorically). Something like 3 seconds would be nicer.

**Comment by vatara** [comment]
This plugin uses the built-in web audio API to do the compression and it looks like release is limited to 0-1.
https://webaudio.github.io/web-audio-api/#dom-dynamicscompressornode-release
https://developer.mozilla.org/en-US/docs/Web/API/DynamicsCompressorNode/release

I tried testing it at 3 seconds in a test version and it sounded the same as 1 to me. So it seems like I can't increase it without the API itself changing.
