### ISSUE TITLE
Icon nearly invisible on dark theme

### ISSUE THREAD

**Issue by seaweed73** [vatara/firefox-audio-compressor#3]
![image](https://user-images.githubusercontent.com/87307342/125268253-d1426e00-e307-11eb-9d98-c9dc8e828a9f.png)
Can you spot the icon? 😄

**Comment by vatara** [comment]
Hmm, it has dark theme support and should work. That is what I use and it shows the light icon for me...what browser version are you using? Is it the Mozilla stock dark theme?

```
"theme_icons": [
      {
        "dark": "data/icons/logo-dark.svg",
        "light": "data/icons/logo-light.svg",
        "size": 16
      }
    ]
```

**Comment by seaweed73** [comment]
ohh I was using the system theme which looks identical
![g9GkoZ3siy](https://user-images.githubusercontent.com/87307342/125336015-821f2c00-e34d-11eb-9ecc-6f2bf864bd45.gif)

**Comment by vatara** [comment]
Ah, I see, it's your operating system that was set to dark. I uploaded a new version that should detect that, once the update gets approved.
