### ISSUE TITLE
TikTik Audio Broken

### ISSUE THREAD

**Issue by xPoP** [vatara/firefox-audio-compressor#9]
The other day I was trying to browse TikTok and realized my audio wouldn't work on my main Chrome profile, but when using incognito, it would output sound normally. If I disable the extension, it alleviates the issue on my main profile.

Great work otherwise and glad I found this tool! Let me know if I can help in any way. Thanks.

Chrome v109.0.5414.120
[Audio Compressor Extension](https://chrome.google.com/webstore/detail/audio-compressor/daomidlfpcfjchpalpjogmnhabkekbnn) v0.1.22 (I understand this Github project is of the Firefox addon so apologies if this is the wrong place to place an issue... The links led me here)
OS Windows 11

**Comment by vatara** [comment]
This is the same problem as issue #2. There's no fix I know of unfortunately. As a workaround, I would save the settings for tiktok.com and set it to disabled, that way it won't try and load on the site.

**Comment by vatara** [comment]
No problem. To disable it just for TikTok, in the plugin UI:
1. click tiktok.com next to "Save settings for"
2. click disabled

![image](https://user-images.githubusercontent.com/850189/216746339-f4effaec-7676-4424-a609-be1d9bd93760.png)

Then it should stay disabled for everywhere on the site.
